# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 205)
        Form.setStyleSheet("/*https://www.realtimecolors.com/?colors=050315-fbfbfe-2f27ce-dedcff-433bff&fonts=Inter-Inter*/\n"
"\n"
".QPushButton{\n"
"background-color:#2f27ce;\n"
"border-radius:3px;\n"
"color:white;\n"
"font-size:2px;\n"
"}\n"
"\n"
".QPushButton::disabled{\n"
"background-color: rgb(146, 150, 206);\n"
"}")
        self.titlebar = QtWidgets.QFrame(Form)
        self.titlebar.setGeometry(QtCore.QRect(-10, 0, 411, 21))
        self.titlebar.setStyleSheet("font: 75 16pt \"Corbel\";\n"
"font-weight:bold;")
        self.titlebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titlebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titlebar.setObjectName("titlebar")
        self.titlebar_header = QtWidgets.QLabel(self.titlebar)
        self.titlebar_header.setGeometry(QtCore.QRect(0, 0, 491, 21))
        self.titlebar_header.setStyleSheet("background-color: rgb(222, 220, 255);")
        self.titlebar_header.setObjectName("titlebar_header")
        self.close_but = QtWidgets.QPushButton(self.titlebar)
        self.close_but.setGeometry(QtCore.QRect(389, 1, 20, 18))
        self.close_but.setStyleSheet("font-size:10px;")
        self.close_but.setObjectName("close_but")
        self.mini_but = QtWidgets.QPushButton(self.titlebar)
        self.mini_but.setGeometry(QtCore.QRect(368, 1, 20, 18))
        self.mini_but.setStyleSheet("font-size:15px;")
        self.mini_but.setObjectName("mini_but")
        self.bg = QtWidgets.QLabel(Form)
        self.bg.setGeometry(QtCore.QRect(-140, -80, 621, 391))
        self.bg.setStyleSheet("background-color: rgb(251, 251, 254);")
        self.bg.setText("")
        self.bg.setObjectName("bg")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(-1, 19, 401, 201))
        self.frame.setStyleSheet("font: 75 16pt \"Corbel\";\n"
"font-weight:bold;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.inject_but = QtWidgets.QPushButton(self.frame)
        self.inject_but.setEnabled(False)
        self.inject_but.setGeometry(QtCore.QRect(70, 50, 271, 61))
        self.inject_but.setStyleSheet("font-size:20px;")
        self.inject_but.setObjectName("inject_but")
        self.extract_but = QtWidgets.QPushButton(self.frame)
        self.extract_but.setEnabled(False)
        self.extract_but.setGeometry(QtCore.QRect(70, 120, 271, 61))
        self.extract_but.setStyleSheet("font-size:20px;")
        self.extract_but.setObjectName("extract_but")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(-10, 1, 420, 3))
        self.line.setStyleSheet("background-color: rgb(47, 39, 206);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(145, 9, 121, 31))
        self.pushButton.setObjectName("pushButton")
        self.bg.raise_()
        self.titlebar.raise_()
        self.frame.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titlebar_header.setText(_translate("Form", "     RSON"))
        self.close_but.setText(_translate("Form", "x"))
        self.mini_but.setText(_translate("Form", "-"))
        self.inject_but.setText(_translate("Form", "inject"))
        self.extract_but.setText(_translate("Form", "extract"))
        self.pushButton.setText(_translate("Form", "ATTACH"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
